2018-06-14T22:58:45.1890728-03:00 0HLEICE37BBLH:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/   (ca22a1cb)
2018-06-14T22:58:47.7596817-03:00 0HLEICE37BBLH:00000001 [INF] Request finished in 2939.4524ms 404  (791a596a)
2018-06-14T22:58:58.2177575-03:00 0HLEICE37BBLJ:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger   (ca22a1cb)
2018-06-14T22:58:58.2523413-03:00 0HLEICE37BBLJ:00000001 [INF] Request finished in 12.9066ms 301  (791a596a)
2018-06-14T22:58:58.3443834-03:00 0HLEICE37BBLJ:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/index.html   (ca22a1cb)
2018-06-14T22:58:58.4188028-03:00 0HLEICE37BBLJ:00000002 [INF] Request finished in 114.7368ms 200 text/html (791a596a)
2018-06-14T22:58:58.4618354-03:00 0HLEICE37BBLK:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/swagger-ui-bundle.js   (ca22a1cb)
2018-06-14T22:58:58.5597683-03:00 0HLEICE37BBLJ:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/swagger-ui.css   (ca22a1cb)
2018-06-14T22:58:58.5678724-03:00 0HLEICE37BBLL:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/swagger-ui-standalone-preset.js   (ca22a1cb)
2018-06-14T22:58:58.5717017-03:00 0HLEICE37BBLJ:00000003 [INF] Sending file. Request path: '"/swagger-ui.css"'. Physical path: '"N/A"' (27b0a520)
2018-06-14T22:58:58.5768801-03:00 0HLEICE37BBLL:00000001 [INF] Sending file. Request path: '"/swagger-ui-standalone-preset.js"'. Physical path: '"N/A"' (27b0a520)
2018-06-14T22:58:58.5802615-03:00 0HLEICE37BBLK:00000001 [INF] Sending file. Request path: '"/swagger-ui-bundle.js"'. Physical path: '"N/A"' (27b0a520)
2018-06-14T22:58:58.7436871-03:00 0HLEICE37BBLJ:00000003 [INF] Request finished in 230.6416ms 200 text/css (791a596a)
2018-06-14T22:58:58.8299081-03:00 0HLEICE37BBLL:00000001 [INF] Request finished in 290.1973ms 200 application/javascript (791a596a)
2018-06-14T22:58:58.8882102-03:00 0HLEICE37BBLK:00000001 [INF] Request finished in 410.8979ms 200 application/javascript (791a596a)
2018-06-14T22:58:59.9258687-03:00 0HLEICE37BBLK:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/v1/swagger.json   (ca22a1cb)
2018-06-14T22:59:00.0086861-03:00 0HLEICE37BBLL:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/favicon-32x32.png   (ca22a1cb)
2018-06-14T22:59:00.0149936-03:00 0HLEICE37BBLL:00000002 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-06-14T22:59:00.0601331-03:00 0HLEICE37BBLL:00000002 [INF] Request finished in 63.4302ms 200 image/png (791a596a)
2018-06-14T22:59:00.1200669-03:00 0HLEICE37BBLL:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/favicon-16x16.png   (ca22a1cb)
2018-06-14T22:59:00.1244378-03:00 0HLEICE37BBLL:00000003 [INF] Sending file. Request path: '"/favicon-16x16.png"'. Physical path: '"N/A"' (27b0a520)
2018-06-14T22:59:00.1311693-03:00 0HLEICE37BBLL:00000003 [INF] Request finished in 26.971ms 200 image/png (791a596a)
2018-06-14T22:59:00.6919258-03:00 0HLEICE37BBLK:00000002 [INF] Request finished in 768.4217ms 200 application/json;charset=utf-8 (791a596a)
2018-06-14T22:59:25.1327453-03:00 0HLEICE37BBLM:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/api/Users   (ca22a1cb)
2018-06-14T22:59:25.7281872-03:00 0HLEICE37BBLM:00000001 [INF] Authorization failed for user: null. (a4ab1676)
2018-06-14T22:59:25.7724475-03:00 0HLEICE37BBLM:00000001 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2018-06-14T22:59:25.8073655-03:00 0HLEICE37BBLM:00000001 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2018-06-14T22:59:25.8192836-03:00 0HLEICE37BBLM:00000001 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2018-06-14T22:59:25.8303470-03:00 0HLEICE37BBLM:00000001 [INF] Executed action "NetCorePoc.Api.Controllers.UsersController.Get (NetCorePoc.Api)" in 164.1312ms (afa2e885)
2018-06-14T22:59:25.8330195-03:00 0HLEICE37BBLM:00000001 [INF] Request finished in 702.0395ms 401  (791a596a)
2018-06-14T23:06:06.4201311-03:00 0HLEICI6U3CC4:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/index.html   (ca22a1cb)
2018-06-14T23:06:06.6859363-03:00 0HLEICI6U3CC4:00000001 [INF] Request finished in 332.3712ms 200 text/html (791a596a)
2018-06-14T23:06:07.6562827-03:00 0HLEICI6U3CC4:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/v1/swagger.json   (ca22a1cb)
2018-06-14T23:06:07.7208076-03:00 0HLEICI6U3CC5:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/favicon-32x32.png   (ca22a1cb)
2018-06-14T23:06:07.8333727-03:00 0HLEICI6U3CC5:00000001 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-06-14T23:06:07.8493379-03:00 0HLEICI6U3CC5:00000001 [INF] Request finished in 141.5483ms 200 image/png (791a596a)
2018-06-14T23:06:08.2541081-03:00 0HLEICI6U3CC4:00000002 [INF] Request finished in 603.3815ms 200 application/json;charset=utf-8 (791a596a)
2018-06-14T23:06:30.2236443-03:00 0HLEICI6U3CCA:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/api/Users   (ca22a1cb)
2018-06-14T23:06:30.4572801-03:00 0HLEICI6U3CCA:00000001 [INF] Authorization failed for user: null. (a4ab1676)
2018-06-14T23:06:30.4673322-03:00 0HLEICI6U3CCA:00000001 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2018-06-14T23:06:30.4911343-03:00 0HLEICI6U3CCA:00000001 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2018-06-14T23:06:30.4993127-03:00 0HLEICI6U3CCA:00000001 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2018-06-14T23:06:30.5115966-03:00 0HLEICI6U3CCA:00000001 [INF] Executed action "NetCorePoc.Api.Controllers.UsersController.Get (NetCorePoc.Api)" in 69.1852ms (afa2e885)
2018-06-14T23:06:30.5228697-03:00 0HLEICI6U3CCA:00000001 [INF] Request finished in 303.8504ms 401  (791a596a)
2018-06-14T23:07:03.2482979-03:00 0HLEICI6U3CCB:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/index.html   (ca22a1cb)
2018-06-14T23:07:03.4187878-03:00 0HLEICI6U3CCB:00000001 [INF] Request finished in 4.1005ms 200 text/html (791a596a)
2018-06-14T23:07:04.0445878-03:00 0HLEICI6U3CCB:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/v1/swagger.json   (ca22a1cb)
2018-06-14T23:07:04.0480833-03:00 0HLEICI6U3CCC:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/favicon-32x32.png   (ca22a1cb)
2018-06-14T23:07:04.0667708-03:00 0HLEICI6U3CCC:00000001 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-06-14T23:07:04.2214378-03:00 0HLEICI6U3CCB:00000002 [INF] Request finished in 52.6041ms 200 application/json;charset=utf-8 (791a596a)
2018-06-14T23:07:04.2327865-03:00 0HLEICI6U3CCC:00000001 [INF] Request finished in 190.2865ms 200 image/png (791a596a)
2018-06-14T23:12:41.8004878-03:00 0HLEICLSOMOC5:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/index.html   (ca22a1cb)
2018-06-14T23:12:41.9867540-03:00 0HLEICLSOMOC5:00000001 [INF] Request finished in 286.5247ms 200 text/html (791a596a)
2018-06-14T23:12:42.6966967-03:00 0HLEICLSOMOC5:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/v1/swagger.json   (ca22a1cb)
2018-06-14T23:12:42.8117591-03:00 0HLEICLSOMOC6:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/favicon-32x32.png   (ca22a1cb)
2018-06-14T23:12:42.8852645-03:00 0HLEICLSOMOC6:00000001 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-06-14T23:12:42.8962327-03:00 0HLEICLSOMOC6:00000001 [INF] Request finished in 97.1611ms 200 image/png (791a596a)
2018-06-14T23:12:43.7093167-03:00 0HLEICLSOMOC5:00000002 [INF] Request finished in 919.2758ms 200 application/json;charset=utf-8 (791a596a)
2018-06-14T23:15:47.0965198-03:00 0HLEICNJSP7FC:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/index.html   (ca22a1cb)
2018-06-14T23:15:47.8185218-03:00 0HLEICNJSP7FC:00000001 [INF] Request finished in 708.5331ms 200 text/html (791a596a)
2018-06-14T23:15:50.0404728-03:00 0HLEICNJSP7FC:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/v1/swagger.json   (ca22a1cb)
2018-06-14T23:15:50.0793926-03:00 0HLEICNJSP7FB:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/swagger/favicon-32x32.png   (ca22a1cb)
2018-06-14T23:15:50.2100121-03:00 0HLEICNJSP7FB:00000001 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2018-06-14T23:15:50.2431041-03:00 0HLEICNJSP7FB:00000001 [INF] Request finished in 224.2163ms 200 image/png (791a596a)
2018-06-14T23:15:51.2000429-03:00 0HLEICNJSP7FC:00000002 [INF] Request finished in 1174.6824ms 200 application/json;charset=utf-8 (791a596a)
2018-06-14T23:19:30.9550960-03:00 0HLEICNJSP7FE:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:5001/NetCorePoc/api/token  0 (ca22a1cb)
2018-06-14T23:19:30.9946395-03:00 0HLEICNJSP7FE:00000001 [INF] Request finished in 10.5978ms 400  (791a596a)
2018-06-14T23:20:01.2994826-03:00 0HLEICNJSP7FE:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:5001/NetCorePoc/api/token  0 (ca22a1cb)
2018-06-14T23:20:29.3811534-03:00 0HLEICNJSP7FE:00000002 [INF] Request finished in 28093.3418ms 400  (791a596a)
2018-06-14T23:21:30.7531726-03:00 0HLEICNJSP7FE:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:5001/NetCorePoc/api/token application/x-www-form-urlencoded 70 (ca22a1cb)
2018-06-14T23:21:55.2467336-03:00 0HLEICNJSP7FE:00000003 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at NetCorePoc.Infrastructure.CrossCutting.Security.TokenProviderMiddleware.CreateJwtSecurityToken(Claim[] claims, String key) in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Infrastructure.CrossCutting.Security\TokenProviderMiddleware.cs:line 162
   at NetCorePoc.Infrastructure.CrossCutting.Security.TokenProviderMiddleware.<CreateToken>d__11.MoveNext() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Infrastructure.CrossCutting.Security\TokenProviderMiddleware.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-06-14T23:21:55.5177316-03:00 0HLEICNJSP7FE:00000003 [INF] Request finished in 24737.7098ms 500 text/html; charset=utf-8 (791a596a)
2018-06-14T23:22:36.6030495-03:00 0HLEICNJSP7FE:00000004 [INF] Request starting HTTP/1.1 POST http://localhost:5001/NetCorePoc/api/token application/x-www-form-urlencoded 69 (ca22a1cb)
2018-06-14T23:22:42.9255268-03:00 0HLEICNJSP7FE:00000004 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at NetCorePoc.Infrastructure.CrossCutting.Security.TokenProviderMiddleware.CreateJwtSecurityToken(Claim[] claims, String key) in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Infrastructure.CrossCutting.Security\TokenProviderMiddleware.cs:line 162
   at NetCorePoc.Infrastructure.CrossCutting.Security.TokenProviderMiddleware.<CreateToken>d__11.MoveNext() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Infrastructure.CrossCutting.Security\TokenProviderMiddleware.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-06-14T23:22:42.9627110-03:00 0HLEICNJSP7FE:00000004 [INF] Request finished in 6426.6841ms 500 text/html; charset=utf-8 (791a596a)
2018-06-14T23:22:50.4901071-03:00 0HLEICNJSP7FE:00000005 [INF] Request starting HTTP/1.1 POST http://localhost:5001/NetCorePoc/api/token application/x-www-form-urlencoded 69 (ca22a1cb)
2018-06-14T23:23:09.7434475-03:00 0HLEICNJSP7FE:00000005 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at NetCorePoc.Infrastructure.CrossCutting.Security.TokenProviderMiddleware.CreateJwtSecurityToken(Claim[] claims, String key) in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Infrastructure.CrossCutting.Security\TokenProviderMiddleware.cs:line 162
   at NetCorePoc.Infrastructure.CrossCutting.Security.TokenProviderMiddleware.<CreateToken>d__11.MoveNext() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Infrastructure.CrossCutting.Security\TokenProviderMiddleware.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-06-14T23:23:09.7880494-03:00 0HLEICNJSP7FE:00000005 [INF] Request finished in 19331.233ms 500 text/html; charset=utf-8 (791a596a)
2018-06-14T23:23:15.4676700-03:00 0HLEICNJSP7FE:00000006 [INF] Request starting HTTP/1.1 POST http://localhost:5001/NetCorePoc/api/token application/x-www-form-urlencoded 83 (ca22a1cb)
2018-06-14T23:23:17.8032876-03:00 0HLEICNJSP7FE:00000006 [INF] Request finished in 2335.459ms 200 application/json (791a596a)
2018-06-14T23:25:01.7794204-03:00 0HLEICNJSP7FE:00000007 [INF] Request starting HTTP/1.1 GET http://localhost:5001/api/users   (ca22a1cb)
2018-06-14T23:25:01.7895345-03:00 0HLEICNJSP7FE:00000007 [INF] "Bearer" was not authenticated. Failure message: "No SecurityTokenValidator available for token: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJOZXRDb3JlQWNjZXNzIiwianRpIjoiZjEzMjY0MDktYThjMC00MDEzLWEyNTItYWJhZWQwZmJkZGE2IiwidXNlciI6IkNhcmxvcyIsImFjY291bnQiOiJNWVJQMTIzNCIsIm5iZiI6MTUyOTAyOTM5NywiZXhwIjoxODQ0Mzg5Mzk3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEifQ.mZ9dFFMWbA4vnV9LrMmnTVKULM8VoYBwWnXyv7J7s2s" (48071232)
2018-06-14T23:25:10.5379286-03:00 0HLEICNJSP7FE:00000007 [INF] Authorization failed for user: null. (a4ab1676)
2018-06-14T23:25:10.5499037-03:00 0HLEICNJSP7FE:00000007 [INF] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2018-06-14T23:25:10.5940228-03:00 0HLEICNJSP7FE:00000007 [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2018-06-14T23:25:10.6031215-03:00 0HLEICNJSP7FE:00000007 [INF] AuthenticationScheme: "Bearer" was challenged. (d45f1f38)
2018-06-14T23:25:10.6122483-03:00 0HLEICNJSP7FE:00000007 [INF] Executed action "NetCorePoc.Api.Controllers.UsersController.Get (NetCorePoc.Api)" in 83.6231ms (afa2e885)
2018-06-14T23:25:11.6356319-03:00 0HLEICNJSP7FE:00000007 [INF] Request finished in 9883.8401ms 401  (791a596a)
2018-06-14T23:25:38.2896601-03:00 0HLEICNJSP7FE:00000008 [INF] Request starting HTTP/1.1 GET http://localhost:5001/api/users   (ca22a1cb)
2018-06-14T23:25:38.3223046-03:00 0HLEICNJSP7FE:00000008 [INF] Successfully validated the token. (60169667)
2018-06-14T23:25:38.3256230-03:00 0HLEICNJSP7FE:00000008 [INF] AuthenticationScheme: "Bearer" was successfully authenticated. (1805f3b3)
2018-06-14T23:25:50.7879974-03:00 0HLEICNJSP7FE:00000008 [INF] Authorization was successful for user: "NetCoreAccess". (d7eb274a)
2018-06-14T23:25:51.9679855-03:00 0HLEICNJSP7FE:00000008 [INF] Executing action method "NetCorePoc.Api.Controllers.UsersController.Get (NetCorePoc.Api)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-06-14T23:25:51.9712088-03:00 0HLEICNJSP7FE:00000008 [INF] Getting all users (20316222)
2018-06-14T23:25:52.6195132-03:00 0HLEICNJSP7FE:00000008 [INF] Entity Framework Core "2.0.0-rtm-26452" initialized '"DomainContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-06-14T23:26:21.8766209-03:00 0HLEICNJSP7FE:00000008 [ERR] An error occurred using the connection to database '"PocDb"' on server '"(localdb)\mssqllocaldb"'. (5fc3407c)
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "PocDb" requested by the login. The login failed.
Login failed for user 'DESKTOP-MNM2DRP\kadu_'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
ClientConnectionId:69268fb8-8aea-462d-93be-db171ddbe378
Error Number:4060,State:1,Class:11
2018-06-14T23:26:22.1917694-03:00 0HLEICNJSP7FE:00000008 [ERR] An exception occurred in the database while iterating the results of a query for context type '"NetCorePoc.Infrastructure.CrossCutting.DataAccess.Context.DomainContext"'."
""System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"PocDb\" requested by the login. The login failed.
Login failed for user 'DESKTOP-MNM2DRP\kadu_'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
ClientConnectionId:69268fb8-8aea-462d-93be-db171ddbe378
Error Number:4060,State:1,Class:11" (64e2593c)
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "PocDb" requested by the login. The login failed.
Login failed for user 'DESKTOP-MNM2DRP\kadu_'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
ClientConnectionId:69268fb8-8aea-462d-93be-db171ddbe378
Error Number:4060,State:1,Class:11
2018-06-14T23:26:30.0478039-03:00 0HLEICNJSP7FE:00000008 [INF] Executed action "NetCorePoc.Api.Controllers.UsersController.Get (NetCorePoc.Api)" in 39224.8902ms (afa2e885)
2018-06-14T23:26:30.4509377-03:00 0HLEICNJSP7FE:00000008 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "PocDb" requested by the login. The login failed.
Login failed for user 'DESKTOP-MNM2DRP\kadu_'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NetCorePoc.Infrastructure.CrossCutting.DataAccess.Repositories.BaseRepository`2.GetAll() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Infrastructure.CrossCutting.DataAccess\Repositories\BaseRepository.cs:line 29
   at NetCorePoc.Domain.Services.UserService.GetUsers() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Domain\Services\UserService.cs:line 24
   at NetCorePoc.Application.Apps.UserAppService.GetUsers() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Application\Apps\UserAppService.cs:line 21
   at NetCorePoc.Api.Controllers.UsersController.Get() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc\Controllers\UsersController.cs:line 34
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
ClientConnectionId:69268fb8-8aea-462d-93be-db171ddbe378
Error Number:4060,State:1,Class:11
2018-06-14T23:26:30.6782116-03:00 0HLEICNJSP7FE:00000008 [INF] Request finished in 52388.3286ms 500 text/html; charset=utf-8 (791a596a)
2018-06-14T23:26:52.9390602-03:00 0HLEICNJSP7FF:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5001/api/Users   (ca22a1cb)
2018-06-14T23:26:52.9723410-03:00 0HLEICNJSP7FF:00000001 [INF] Successfully validated the token. (60169667)
2018-06-14T23:26:52.9770960-03:00 0HLEICNJSP7FF:00000001 [INF] AuthenticationScheme: "Bearer" was successfully authenticated. (1805f3b3)
2018-06-14T23:26:57.2776430-03:00 0HLEICNJSP7FF:00000001 [INF] Authorization was successful for user: "NetCoreAccess". (d7eb274a)
2018-06-14T23:26:57.3525288-03:00 0HLEICNJSP7FF:00000001 [INF] Executing action method "NetCorePoc.Api.Controllers.UsersController.Get (NetCorePoc.Api)" with arguments (null) - ModelState is Valid (ba7f4ac2)
2018-06-14T23:26:57.3580632-03:00 0HLEICNJSP7FF:00000001 [INF] Getting all users (20316222)
2018-06-14T23:26:57.3670981-03:00 0HLEICNJSP7FF:00000001 [INF] Entity Framework Core "2.0.0-rtm-26452" initialized '"DomainContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "None" (9958f5bb)
2018-06-14T23:27:07.5778330-03:00 0HLEICNJSP7FF:00000001 [ERR] An error occurred using the connection to database '"PocDb"' on server '"(localdb)\mssqllocaldb"'. (5fc3407c)
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "PocDb" requested by the login. The login failed.
Login failed for user 'DESKTOP-MNM2DRP\kadu_'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
ClientConnectionId:59974697-e98b-48fd-a32d-4633495fb46c
Error Number:4060,State:1,Class:11
2018-06-14T23:27:07.7433475-03:00 0HLEICNJSP7FF:00000001 [ERR] An exception occurred in the database while iterating the results of a query for context type '"NetCorePoc.Infrastructure.CrossCutting.DataAccess.Context.DomainContext"'."
""System.Data.SqlClient.SqlException (0x80131904): Cannot open database \"PocDb\" requested by the login. The login failed.
Login failed for user 'DESKTOP-MNM2DRP\kadu_'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
ClientConnectionId:59974697-e98b-48fd-a32d-4633495fb46c
Error Number:4060,State:1,Class:11" (64e2593c)
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "PocDb" requested by the login. The login failed.
Login failed for user 'DESKTOP-MNM2DRP\kadu_'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NetCorePoc.Infrastructure.CrossCutting.DataAccess.Repositories.BaseRepository`2.GetAll() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Infrastructure.CrossCutting.DataAccess\Repositories\BaseRepository.cs:line 29
   at NetCorePoc.Domain.Services.UserService.GetUsers() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Domain\Services\UserService.cs:line 24
   at NetCorePoc.Application.Apps.UserAppService.GetUsers() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Application\Apps\UserAppService.cs:line 21
   at NetCorePoc.Api.Controllers.UsersController.Get() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc\Controllers\UsersController.cs:line 34
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
ClientConnectionId:59974697-e98b-48fd-a32d-4633495fb46c
Error Number:4060,State:1,Class:11
2018-06-14T23:27:13.4744440-03:00 0HLEICNJSP7FF:00000001 [INF] Executed action "NetCorePoc.Api.Controllers.UsersController.Get (NetCorePoc.Api)" in 16200.9301ms (afa2e885)
2018-06-14T23:27:14.0525122-03:00 0HLEICNJSP7FF:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "PocDb" requested by the login. The login failed.
Login failed for user 'DESKTOP-MNM2DRP\kadu_'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NetCorePoc.Infrastructure.CrossCutting.DataAccess.Repositories.BaseRepository`2.GetAll() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Infrastructure.CrossCutting.DataAccess\Repositories\BaseRepository.cs:line 29
   at NetCorePoc.Domain.Services.UserService.GetUsers() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Domain\Services\UserService.cs:line 24
   at NetCorePoc.Application.Apps.UserAppService.GetUsers() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc.Application\Apps\UserAppService.cs:line 21
   at NetCorePoc.Api.Controllers.UsersController.Get() in C:\Users\kadu_\repo\NetCorePoc\NetCorePoc\Controllers\UsersController.cs:line 34
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
ClientConnectionId:59974697-e98b-48fd-a32d-4633495fb46c
Error Number:4060,State:1,Class:11
2018-06-14T23:27:14.2986801-03:00 0HLEICNJSP7FF:00000001 [INF] Request finished in 21331.8571ms 500 text/html; charset=utf-8 (791a596a)
